### ISSUE TITLE
getting started sequence

### ISSUE THREAD

**Issue by tomtruitt** [eris-ltd/docs.erisindustries.com#102]
sorry not sure if this is an issue or my own ignorance but in the getting-started tut step one is install eris and step two is make a simplechain. i get an api error about not being able to get container for eris_service_keys1. it seems this is missing a step to start eris keys?

**Comment by compleatang** [comment]
fixed after you previously noted this error.

![screenshot-docs erisindustries com 2016-04-02 20-28-24](https://cloud.githubusercontent.com/assets/590037/14228315/9e56d70a-f911-11e5-8f03-9190257378ab.png)
