### ISSUE TITLE
chain-making.md

### ISSUE THREAD

**Issue by tomtruitt** [eris-ltd/docs.erisindustries.com#103]
"The config.toml file is generally edited to fill in the seeds and moniker fields. The seeds field (which is a misnomer because it accepts a string rather than an array, and as such should have been named seed) is used to point your consensus engine to the peer server it should connect into. For more information on how to deal with this please see our advanced chain making tutorial. "

config.toml doesn't seem to be covered in the advanced chain making tutorial as implied... I am curious about this since when I had used the blocklab tool in the past only one peer host was set in the config.toml after being asked which host would be the peer server... also in this chain-making tutorial the concept of a "peer sergeant major" sounds like one node would be responsible for this.. also in the passage I quoted it says seed vs seeds. 

this is all confusing to me because seeds does accept a comma delimited list and in fact if i recall correctly Jae had suggested when i was troubleshooting the chain i had set up with blocklab that i should have all my validators listed there so they may all seed to the others... this really only makes sense since what happens if my seed host goes down?

**Comment by AFDudley** [comment]
Yeah, there are some issues here, it's good to raise them. it should still be called "seeds" because it can take multiple seeds in the same string. BUT! I'm not sure that actually makes a lot of sense, I'm pretty sure they should boot from the "First Administrative node" and that this shouldn't be a parameter at all, in part because it's so confusing.

**Comment by tomtruitt** [comment]
it doesn't address your thoughts on booting from "first administrative node" (does/should a chain require an adminstrative node?) but i did submit a pull to change this doc to mention adding additional seeds... personally i don't believe that having a single point of failure is acceptable.

**Comment by tomtruitt** [comment]
jae [1:28 PM] 
currently there’s no peer-exchange/discover mechanism.  There was one with the pex_handler but that’s been taken out temporarily.  We will add it back later this year.

[1:28] 
So for now seeds is best thought of as "peers"

[1:28] 
You really do want all your connected peers in the “seeds” config.

[1:28] 
There’s another way to set this though… mintnet passes in the “seeds” via an RPC call.

**Comment by tomtruitt** [comment]
i'm sure eris has some peer-exchange mechanism? but jae has said a few times to list all the peers here..

**Comment by compleatang** [comment]
we use config files a lot more than rpc calls. in any event, i like you're edits so we'll stick to that and close this issue for now.
