### ISSUE TITLE
Eris by Curl outdated + dead link

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/docs.erisindustries.com#113]
The tutorial of [Eris by Curl](https://docs.erisindustries.com/tutorials/tool-specific/eris_by_curl/) is outdated, the link to the bash script is dead, the [actual content](https://github.com/eris-ltd/mint-client/blob/master/example/example.sh) seems to have changed with respect to the webpage. I dont know what version is more up to date hence no PR from my side.

**Comment by zramsay** [comment]
Hi @SCBuergel, unfortunately, this explainer is no longer maintained.
