### ISSUE TITLE
chain-deploying tutorial

### ISSUE THREAD

**Issue by tomtruitt** [eris-ltd/docs.erisindustries.com#117]
so i know i was a staunch advocate of all peers being listed in the seeds field of the config.toml. but what experience has shown me is that in fact when one creates new validators often and applies the same chain to it for devolopment, ip's will frequently change aside from the admin machine. after further learning about the concept of an address book and noticing that that it seems more efficient to have the admin as the one constant "peer sergeant" as long deployed before the other nodes then syncing seems to go smoothly (when this didn't go smoothly it could be for having fast sync on admin node and false for others). this saves time editing file every time and allows one to easily create vms start a new chain with minimal bash knowledge. i'd try and make some kind of usefel commit but i'm drunk and tired...

**Comment by tomtruitt** [comment]
this would require a slight refactoring of the tut if this logic is to be passed on since the tut reads to connect the admin node last

**Comment by zramsay** [comment]
happy to re-visit if you've got a more concrete proposal.
