### ISSUE TITLE
Description either unclear or incorrect in Contracts tutorial.

### ISSUE THREAD

**Issue by TrySpace** [eris-ltd/docs.erisindustries.com#147]
Here: https://docs.erisindustries.com/tutorials/contracts-deploying/#tocAnchor-1-6 at `Job 3`

It talks about 

> 
The job is pulling the value of the `$setStorage` job (eris:package_manager knows this because it resolved $ + jobName to the result of the `setStorage` job) and replacing that with the value, which is 5.

Is this not supposed to be `$setStorageBase` because that's where you assign the `val` of 5.

Or is it resolving the `Base` part? in which case, this is not clearly explained.

(Also there's a typo: `procede` instead of `proceed`)

**Comment by compleatang** [comment]
@TrySpace thanks for that! Tutorial is updated. Indeed it should have been the `setStorageBase` job not the `setStorage` job. (also typo fixed!)

:+1:
