### ISSUE TITLE
Typos/syntax/additions in docs

### ISSUE THREAD

**Issue by TrySpace** [eris-ltd/docs.erisindustries.com#148]
Couple of things while following the `getting-started` tutorial.

Typo: https://docs.erisindustries.com/tutorials/contracts-interacting/
`transaciton`

https://docs.erisindustries.com/tutorials/services-making/
> What we are going to change up the old idi contract so that it does a few things for us which will be helpful for us to learn about docker and eris later. 
Either put `is` after `change up`, or remove `What`. And maybe insert a comma after `for us`

https://docs.erisindustries.com/tutorials/services-making/
After `eris services`, before you copy or `curl` the `app.js`, there should be a line `cd idi-services` after `cp -r idi idi-service # or whatever you would like to call it`, just for consistency. (and not later like it is now, before you run the `app.js`)
(Also the `curl` snippet is now at the top of the code instead of the bottom, like before. I think this should be consistent with the rest as well)

https://docs.erisindustries.com/tutorials/services-making/
1.When I start the `app.js` in Windows I get the error:
```
 internal/net.js:17
    throw new RangeError('"port" argument must be >= 0 and < 65536');
    ^
```
And when I manually set them, it does run.. (I'm using git-bash with docker quickstart terminal on win10x64) 
Note: It does run with port `undefined` like it should, without errors, when it runs as a `service`...
Note: On Linux it does output like it does in the docs, as `undefined`

2. "Then open the Dockerfile in your favorite text editor." next is the line of code that should be in the Dockerfile, but this could just as well be terminal command. Most will understand it's not, but for clarity perhaps say: "Then open the Dockerfile in your favorite text editor, and add the following line:"

3. Is it correct the `Dockerfile` only has one line? `FROM node:4-onbuild`, because later in troubleshooting I see a `Dockerfile` with `CMD`'s and `npm install`?

4. "your dockerfile too look something like this:" *to

5. "Chrome “channels” than like git “branches”." would be "rather than git"

6. "Edit your idi service definition file to look like this:" There's only 2 two lines, and it is unclear where to put those. And that sentence implies that my file should look like it, not add the lines. ( I see it needs to be under `[service]` )

7. "You should substitute idi/ for your username (+ a / :-) )" I would replace that with "You should subsitute `idi/` with your username, like: `username/`

8. Perhaps mention to use `docker login` to login before you `docker push`

9. `eris services start ipfs`, gives an error:
`Bind for 0.0.0.0:8080 failed: port is already allocated`
(When I change the ports in `idi.toml` to something else, it will run. But apparently they both use the same `8080` port...)

Lastly. Trying: `eris services import idi QmUxawH7yTQxPh4HZLSC1FsWGYy3XhJaBrhshZd78HWgkX && eris services start idi` on a remote device, errors that `the service definition file looks improperly formatted and will not marshall`. Locally however it will run (but it already has it). Not sure what is wrong there. Wouldn't `docker pull x` be sufficient?

I was so close to completely finishing the tutorial :'(

Oh, and I never got what `idi` stands for...

Very good, solid and complete tutorials in general, just some sentences need some more comma's or be shorter. Like split a long sentence up in two etc.
Hope none of this comes off as nit-picky, I just want to streamline this for the next person, for the community.

**Comment by compleatang** [comment]
:+1: great, great comments! thanks so much.

`idi` -> (tongue in cheek reference to a dictator: idi amin)

not sure why the import is failing on you, could be on ipfs's side or ours... can you dump what is pulled from that here or in a new ticket. either way you should use the hash that you exported rather than the one in the tutorial...
