### ISSUE TITLE
TypeError: contract.abi.filter is not a function

### ISSUE THREAD

**Issue by datafluisteraar** [eris-ltd/docs.erisindustries.com#61]
Dear Eris, i struggled my way through the tutorial (https://docs.erisindustries.com/tutorials/servicesmaking/) and ended up here, ie the TypeError. Idi is working fine as you can see from this image.
![capture](https://cloud.githubusercontent.com/assets/16633366/12535255/65a1a040-c27d-11e5-8c3d-216861848032.JPG)
I'm stucked trying to get idi-service up & running. Can't get this figured out.

Any clue?! Please be with me. Learning on the job. No experience yet with nodejs.

PS
There's a comma missing at the end of 'chainUrl = "http://localhost:1337/rpc"' in the new app.js on your website example, isn't it?

**Comment by datafluisteraar** [comment]
Got it running by
- modifying chainUrl
- thourough study & application of code at https://www.npmjs.com/package/eris-contracts
- changing abi by copied array

![capture](https://cloud.githubusercontent.com/assets/16633366/12535794/2deb7c72-c28f-11e5-87d1-b6b194747f26.JPG)

This is what I changed in the original app.js

// Taken from https://www.npmjs.com/package/eris-contracts
// ************
// <copy>
var myExistingContract;

// Create a factory for the contract with the JSON interface 'myAbi'.
var myContractFactory = manager.newContractFactory(JSON.parse('[{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"type":"function"}]',{encoding:'utf8'}));

myContractFactory.at(address, function(error, contract){
    if (error) {
        // Something.
        throw error;
    }
    myExistingContract = contract;
});
// <paste> & modified
// replaced contract underneath at rows 43 & 55 by myExistingContract
// ************

**Comment by compleatang** [comment]
Super! Glad to hear it is back working for you. Closing for now but if there is specific feedback on the script let us know or send us a Pull Request and we'll definitely talk through it.
