### ISSUE TITLE
apt-get installation fails for Ubuntu wily

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/docs.erisindustries.com#62]
I am installing Eris on a clean Ubuntu install (15.10 x64) using [apt-get](https://github.com/eris-ltd/docs.erisindustries.com/blob/master/tutorials/getting-started.md#apt-get-installation) and ran into the following issue:
 
    $ lsb_release -c
    Codename:	wily
    $ sudo echo "deb https://apt.eris.industries wily main" > /etc/apt/sources.list.d/eris.list
    bash: /etc/apt/sources.list.d/eris.list: Permission denied

**Comment by SCBuergel** [comment]
Is wily not supported? Manually editing `/etc/apt/sources.list.d/eris.list` and adding `deb https://apt.eris.industries wily main` into it results in:

    $ sudo apt-get update
    [...]
    W: Failed to fetch https://apt.eris.industries/dists/wily/main/binary-amd64/Packages  HttpError404
    W: Failed to fetch https://apt.eris.industries/dists/wily/main/binary-i386/Packages  HttpError404
    E: Some index files failed to download. They have been ignored, or old ones used instead.

If I change the distribution from `wily` to `vivid` the installer works fine. Now I'm about to find out if this leads to serious issues later on ;-)

**Comment by compleatang** [comment]
Thanks SC for the Edits. We'll at those to the tut so that others may benefit. Adding `wily` now, thanks for the reminder.

**Comment by compleatang** [comment]
`wily` added. Let us know if any problems.

**Comment by SCBuergel** [comment]
[The marmots killed the docker, could only help myself with a re-install]
Just tried and it works, thank you!

Still I had to manually copy `deb https://apt.eris.industries wily main` into `/etc/apt/sources.list.d/eris.list`, the sudo echo command did not get permission.

**Comment by compleatang** [comment]
:+1:
