### ISSUE TITLE
Change ordering - advanced chainmaking tutorial

### ISSUE THREAD

**Issue by lsseckman** [eris-ltd/docs.erisindustries.com#77]
Little confusion [here](https://docs.erisindustries.com/tutorials/advanced/chainmaking/#tocAnchor-1-5) as it tells the user to stop the chain before running the exec command. 

The best place for the `eris chains stop <name>` command might be right above the `eris chains rm --data` command.

**Comment by compleatang** [comment]
++ (that tut needs a refresh anyway).

**Comment by compleatang** [comment]
the reason we had the `stop` and then the `exec` is because in older versions the execs would fail if there wasn't a data container in existence. that's fixed now so this can get refactored soon to be more simple.

**Comment by compleatang** [comment]
++ this should be fixed and much clearer now.
