### ISSUE TITLE
add eris:cm to core reference

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/docs.erisindustries.com#82]

**Comment by compleatang** [comment]
what do you mean by "core reference" here? cm is currently available in /documentation/index.md

**Comment by zramsay** [comment]
![screen shot 2016-03-23 at 6 02 41 pm](https://cloud.githubusercontent.com/assets/8304391/14005538/82d4d5ba-f121-11e5-8a14-faa22c91704d.png) (easier than words)
