### ISSUE TITLE
getting started sequence

### ISSUE THREAD

**Issue by tomtruitt** [eris-ltd/docs.erisindustries.com#97]
sorry not sure if this is an issue or my own ignorance but in the getting started tut step one in install eris and step two is say to make a simplechain. i get an api error about not being able to get container for eris_service_keys1. i know in the advanced tutorial it says to run eris keys service first...

**Comment by compleatang** [comment]
:+1:

**Comment by tomtruitt** [comment]
ahh sorry missed this

**Comment by compleatang** [comment]
No worries! Was a good catch... Thanks!
